### ISSUE TITLE
Error from Stripe: There was an unexpected error -- try again in a few seconds

### ISSUE THREAD

**Issue by t-kietzmann** [wilpar/payment_intent#1]
Hey wilpar,

thanks for your work - but this solution does not work.

The PaymentIntent works succesfull to the correct connect user and a payment is placed, but the bottom sheet from flutter_stripe 2.0.2 disappears immediately so you can not finish the payment.

Flutter gives me the error:
No such payment_intent: 'pi_3JwBfFICQYHd3D1Y0B7NXIP1', stripeErrorCode: resource_missing, declineCode: null, type: invalid_request_error

Do you have any experience with this?

All the best
Tobi

**Comment by t-kietzmann** [comment]
//Edit: I didn't set the acct_ number on the frontend, now it works.

**Comment by wilpar** [comment]
Glad you got it sorted!
